name: easy_stock_app
description: A new Flutter project for stock management.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  carousel_slider: ^5.0.0
  # # google_fonts: ^6.2.1
  # shared_preferences: ^2.2.2
  # dotted_border: ^2.1.0
  # image_picker: ^1.1.2
  # # flutter_screenutil: ^5.9.0
  # # flutter_barcode_scanner: ^2.0.0
  # flutter_secure_storage: ^9.2.2
  # flutter_secure_token_manager: ^0.0.1
  # http: ^1.2.2
  # flutter_typeahead: ^4.0.0
  # path: ^1.9.0
  # intl: ^0.19.0
  # another_flushbar: ^1.12.30


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Add assets to your application.
  assets:
  - assets/images/

  # Define custom fonts here.
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: fonts/Poppins-Regular.ttf
  #       - asset: fonts/Poppins-Bold.ttf
  #         weight: 700
  #       - asset: fonts/Poppins-Medium.ttf
  #         weight: 500
